### ISSUE TITLE
Extension keeps crashing

### ISSUE THREAD

**Issue by mylosol** [Leo-ajc/ProTip#3]
I continue to have this persistent problem, the extension never stays working very long.
I have uninstalled and reinstalled the extension from the Chrome Store and my.protip.is and after a little bit the extension crashes.  In my extension menu is shows "This extension may have been corrupted".  The repair option fixes the problem only for a short time, but the corrupt error message always returns. 
![protip](https://cloud.githubusercontent.com/assets/13090110/10726972/5bfcd656-7ba4-11e5-8533-618d39da6496.PNG)

**Comment by MrChrisJ** [comment]
Hey @mylosol yes we have now identified this issue that some users were experiencing with corruption when restarting Chrome. We fixed this [over the weekend](https://twitter.com/MrChrisEllis/status/657996555128057860) but are currently testing the patch to make sure that we haven't introduced any new bugs. New stable released should be out later this week.

If you would like to you could become one of our testers and I can send you a link to the Edge version. Also if you send me your Bitcoin address I will add you to our new bitcoin faucet feature which we are currently testing out.

Thanks for your time.

**Comment by Leo-ajc** [comment]
Hi Mylosol,

We have this fixed this issue and it will be in the next release. It is due in the next couple of days. It will auto update from the chrome store. I am sorry you have had to encounter this issue.

The coming release, v1.0.0.26, will have additional features and stability improvements. We are working to get Protip into a stable release as soon as possible. 

However thanks for the bug report. It was hard to fix because it works perfectly when deployed locally but only shows up when downloaded from the Chrome Store.

The issue took us sometime to isolate, it is a bug in chrome that accepts relative file paths starting starting with './' when deployed locally and on initial installation from Chrome Store. But sometimes when it tries to do a a security check, typically when it is disabled and reenabled, it thinks that the downloaded source doesn't match the recorded manifest. Removing the './' prefix, fixed the issue.

**Comment by mylosol** [comment]
Chris,

     Thank you for your fast responce and for developing this extension, I
love the concept and functionality.  I would love to be an Edge tester if
it can help further development, once I get a stable release I will also
promptly set up a my.protip.is subscription as well to help fund said
further development.  I believe people like you and programs like this will
be the future of how we fund creators on the web.  My Bitcoin address
is 1EKTdmRizEwPSeCq6NWc9DaW35ydDoYLft
and I would love to be a part of the bitcoin faucet feature as well...
